MEASUREMENT_ACTIVE = False
PAUSE_ACTIVE = False
BATTERY_LEVEL = 0
MEASUREMENT_DISTANCE = 0
MEASUREMENT_VALUE = 0

RUNNING_MEASUREMENT = None
STREET_WIDTH = 0
LIMIT_VALUE = 0
VIEW_VALUES = []
LONGTERM_VALUES = []

